openapi: 3.0.0
servers:
  - description: A dev server endpoint
    url: http://192.168.1.84/cg/actuator/switch
info:
  version: "1.0.0"
  title: cg-switch-remote-control-api
  description: |
    Switch Remote Control API. Allows remote control switch,
    consisting of ESP8266 and SRD-05VDC-SL-C relay.
paths:
  "/{deviceId}/state":
    get:
      tags:
        - device
          ESP8266
          SRD-05VDC-SL-C
      description: Returns device state
      operationId: getDeviceState
      parameters:
        - in: path
          name: deviceId
          description: Device unique identifier
          schema:
            $ref: "#/components/schemas/DeviceIdType"
          examples:
            deviceIdTypeExample:
              $ref: "#/components/examples/DeviceIdTypeExample"
          required: true
      responses:
        "200":
          description: The device state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceStateType"
              examples:
                deviceStateTypeExample:
                  $ref: "#/components/examples/DeviceStateTypeExample"
        "500":
          description: Internal device error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
    post:
      tags:
        - device
          ESP8266
          SRD-05VDC-SL-C
      operationId: setDeviceSet
      parameters:
        - in: path
          name: deviceId
          description: Device unique identifier
          schema:
            $ref: "#/components/schemas/DeviceIdType"
          examples:
            deviceIdTypeExample:
              $ref: "#/components/examples/DeviceIdTypeExample"
          required: true
      responses:
        "200":
          description: Successfully set device state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceStateType"
              examples:
                deviceStateTypeExample:
                  $ref: "#/components/examples/DeviceStateTypeExample"
        "400":
          description: Request message validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorValidationExample:
                  $ref: "#/components/examples/ErrorValidationExample"
        "500":
          description: Internal device error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceStateUpdateType"
            examples:
              deviceStateUpdateTypeExample:
                $ref: "#/components/examples/DeviceStateUpdateTypeExample"
components:
  schemas:
    DeviceIdType:
      type: string
      description: Device unique identifier
      example: "0001"
    PlugType:
      type: integer
      description: SRD-05VDC-SL-C single plug state
      minimum: 0
      maximum: 1
      example: 1
    DeviceStateUpdateType:
      type: object
      description: SRD-05VDC-SL-C plugs states for the device state update
      properties:
        plug1:
          $ref: "#/components/schemas/PlugType"
        plug2:
          $ref: "#/components/schemas/PlugType"
        plug3:
          $ref: "#/components/schemas/PlugType"
        plug4:
          $ref: "#/components/schemas/PlugType"
    DeviceStateType:
      type: object
      description: SRD-05VDC-SL-C current state
      properties:
        deviceType:
          type: string
          description: Device type description
          example: switch
        deviceId:
          type: string
          description: Device unique identifier
          example: "0001"
        deviceTags:
          type: array
          description: Device description tags
          items:
            type: string
            description: Single device description tag
            example: SRD-05VDC-SL-C
        plug1:
          $ref: "#/components/schemas/PlugType"
        plug2:
          $ref: "#/components/schemas/PlugType"
        plug3:
          $ref: "#/components/schemas/PlugType"
        plug4:
          $ref: "#/components/schemas/PlugType"
    Error:
      type: object
      properties:
        errorCode:
          description: Unique error code
          type: string
          maxLength: 6
        errorMsg:
          description: Detailed error description
          type: string
  examples:
    DeviceIdTypeExample:
      value: "0001"
    DeviceStateUpdateTypeExample:
      value:
        plug1: 1
        plug2: 1
        plug3: 0
        plug4: 0
    DeviceStateTypeExample:
      value:
        deviceType: switch
        deviceId: "0001"
        deviceTags:
          - SRD-05VDC-SL-C
        plug1: 1
        plug2: 1
        plug3: 0
        plug4: 0
    ErrorValidationExample:
      value:
        errorCode: "0001"
        errorMsg: InvalidInput
    ErrorInternalExample:
      value:
        errorCode: "0002"
        errorMsg: Internal device error
